#!/bin/sh

# Code sign and notarize an app for local distribution in a DMG file.
# 
# MAKE SURE COMMAND LINE UTILS MATCH THE VERSION OF XCODE BEING USED
#
# 1) Xcode: Archive app
# 2) Xcode: Distribute code signed app (not notarized)
#           Name the created folder GeoTag.
# 3) Run this script to create a READ ONLY DMG
# 4) Note the returned Request-UUID.
# 5) Check status using this command:
#    xcrun altool --notarization-info Request-UUID --username "marc+developer@snafu.org" --password "@keychain:Notarizing"
# 6) Wait until that status is "Package Approved" -- or you get an email from apple
# 7) Staple the notarization ticket to the dmg
#    xcrun stapler staple -v ${DMG}

set -ex

BUILD_VERSION=$(git describe --tags --always --dirty=+)
LATEST_TAG=$(git describe --tags --match 'v*' --abbrev=0 2>/dev/null) || LATEST_TAG="HEAD"
if [ $LATEST_TAG = "HEAD" ]; then
    SHORT_VERSION="0.0.$BUNDLE_VERSION"
else
    COMMIT_COUNT_SINCE_TAG=$(git rev-list --count ${LATEST_TAG}..HEAD)
    if [ ${COMMIT_COUNT_SINCE_TAG} -eq 0 ]; then
        SHORT_VERSION=${LATEST_TAG##v}
    else
        SHORT_VERSION=${LATEST_TAG##v}.${COMMIT_COUNT_SINCE_TAG}
    fi
fi
NAME=GeoTag-${SHORT_VERSION}
DIR=~/Desktop/${NAME}
DMG=~/Desktop/${NAME}.dmg

rm -rf ${DIR}
mkdir ${DIR}

ln -s /Applications ${DIR}
cp -R ~/Desktop/GeoTag/GeoTag.app ${DIR}
cp README ${DIR}/Readme.txt
echo ${BUILD_VERSION} > ${DIR}/Version.txt

rm -f ${DMG}
hdiutil create -srcfolder ${DIR} -volname ${NAME} -format UDZO ${DMG}
rm -rf ${DIR}

# use `security find-identity -p codesigning` to find the appropriate ID

codesign --deep --force --verify --verbose -s 1BC4A429EE4A7435268EA4605A22C535E80049EE --options runtime ${DMG}

# Upload to apple for notarization.  Use org.snafu.$NAME as the bundle ID

xcrun altool -type osx --notarize-app --primary-bundle-id "org.snafu.${NAME}" --username "marc+developer@snafu.org" --password "@keychain:Notarizing" --file ${DMG}

exit 0