#!/bin/sh

# Code sign and notarize an app for local distribution in a DMG file.
# 
# MAKE SURE COMMAND LINE UTILS MATCH THE VERSION OF XCODE BEING USED
#
# 1) Xcode: Archive app
# 2) Notarize App
# 3) Export Notarized app.  It will wind up on the Desktop
# 4) Run this script to create a notarized READ ONLY DMG
#
# Script changed to use notarytool in place of altool.  Notarytool
# store credentials named "notary-snafu.org" were created using this command:
#   xcrun notarytool store-credentials \
#       --apple-id "marc+developer@snafu.org" \
#       --team-id "A3UXBEBE8Z"
# then entering the profile name and the "Notarizing" password stored in
# the keychain.

set -ex

BUILD_VERSION=$(git describe --tags --always --dirty=+)
LATEST_TAG=$(git describe --tags --match 'v*' --abbrev=0 2>/dev/null) || LATEST_TAG="HEAD"
if [ $LATEST_TAG = "HEAD" ]; then
    SHORT_VERSION="0.0.$BUNDLE_VERSION"
else
    COMMIT_COUNT_SINCE_TAG=$(git rev-list --count ${LATEST_TAG}..HEAD)
    if [ ${COMMIT_COUNT_SINCE_TAG} -eq 0 ]; then
        SHORT_VERSION=${LATEST_TAG##v}
    else
        SHORT_VERSION=${LATEST_TAG##v}.${COMMIT_COUNT_SINCE_TAG}
    fi
fi
NAME=GeoTag-${SHORT_VERSION}
WORK=~/Desktop/${NAME}-work.dmg
DIR=/Volumes/${NAME}
DMG=~/Desktop/${NAME}.dmg

# create read/write DMG and open it
rm -rf ${WORK}
hdiutil create -size 100m -fs 'Case-sensitive APFS' -volname ${NAME} ${WORK}
open ${WORK}
sleep 2 # give time for the volume to open
open ${DIR}

# Add a background image
BG_DIR=${DIR}/.background
mkdir ${BG_DIR}
cp background.png ${BG_DIR}

# Add the files and Applications link
ln -s /Applications ${DIR}
cp -R ~/Desktop/GeoTag.app ${DIR}
cp README.md ${DIR}/Readme.txt
echo ${BUILD_VERSION} > ${DIR}/Version.txt

# make it look pretty
./pretty-dmg ${NAME}

# use a custom icon on the mounted volume
cp -a VolumeIcon.icns ${DIR}/.VolumeIcon.icns
xattr -wx com.apple.FinderInfo \
    "00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00
     00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00" ${DIR}

# unmount the volume
hdiutil eject "/Volumes/${NAME}"

# convert the DNG to format UDZ0 and clean up
rm -f ${DMG}
hdiutil convert ${WORK} -ov -format UDZO -imagekey zlib-level=9 -o ${DMG}
rm -rf ${WORK}

# codesign the dmg
# use `security find-identity -p codesigning` to find the appropriate ID

codesign --deep --force --verify --verbose -s E10980DD546B75632A861AD57624C14BDA78A155 --options runtime ${DMG}

# Upload to apple for notarization.

xcrun notarytool submit ${DMG} \
    --keychain-profile "notary-snafu.org" \
    --wait

xcrun stapler staple -v ${DMG}

exit 0
